### ISSUE TITLE
Block quotes are formatted weirdly

### ISSUE THREAD

**Issue by chumbud** [Adjective-Object/markdown-live#21]
![vivaldi_2016-09-13_14-13-32](https://cloud.githubusercontent.com/assets/3811510/18485807/61944484-79bc-11e6-865f-c9dfa42ee9a8.png)

No matter how many new lines I put in, it don't change.

**Comment by Adjective-Object** [comment]
whats weird here?

**Comment by chumbud** [comment]
should be equally spaced top and bottom, right?

**Comment by daanvanham** [comment]
This issue was caused by multiple css properties overriding each other. After a quick look in the css file, I saw there were more 'issues' like this. `H1` in the `markdown-document.scss` for example:

```
h1 {
  font-size: 2em;
  margin: .67em 0;
  font-size: 30px;
  padding-bottom: .3em;
  font-size: 2.25em;
  line-height: 1.2;
  border-bottom: 1px solid $gallery_approx;
  margin-top: 15px;
  margin-bottom: 15px;
  line-height: 1.1;
  position: relative;
  margin-top: 1em;
  margin-bottom: 16px;
  font-weight: bold;
  line-height: 1.4;
}
```
- `line-height` - declared 3 times
- `font-size` - declared 3 times
- `margin` - declared 1 time
- `margin-bottom` - declared 2 times
- `margin-top` - declared 2 times

Maybe a clean-up of the file would prevent these kinds of issues.
